name: CommonAppleKitJobs

on:
  push:
    branches:
      - main

jobs:
  test:
    name: CommonAppleKitTests
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 15.0
      - name: Build
        run: swift build -v
